e_commerce/dj_e_commerce/urls.py
from django.urls import path
from .views import  *

app_name = 'dj_e_commerce'
urlpatterns = [
    path('', HomeView.as_view(), name = 'home'),
    path('product/<slug>/', ItemDetailView.as_view(), name = 'product'),
    path('checkout/',CheckOutView.as_view(), name = 'checkout'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('signup/', signup, name='signup'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('increase-quantity/<slug>/', increase_quantity, name='increase-quantity'),
    path('decrease-quantity/<slug>/', decrease_quantity, name='decrease-quantity'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),

]

e_commerce/e_commerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), # new
    path('', include ('dj_e_commerce.urls', namespace='dj_e_commerce')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_commerce/dj_e_commerce/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField

User = get_user_model()

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)
ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

class Item(models.Model):
    title = models.CharField(max_length= 100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null= True)
    description = models.CharField (max_length= 1000, blank= True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length= 10, default='S')
    label = models.CharField(choices=LABEL_CHOICES, max_length= 10, default='P')
    slug = models.SlugField(unique= True)
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse ('dj_e_commerce:product', kwargs = {'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse ('dj_e_commerce:add-to-cart', kwargs = {'slug': self.slug})

    def get_price(self):
        if (self.discount_price):
            return self.discount_price
        return self.price



class OrderItem(models.Model):
    item = models.ForeignKey (Item , on_delete= models.CASCADE)
    quantity = models.IntegerField (default= 1)


    def __str__(self):
        return str(self.item.title) + str(self.quantity)

    def get_total_price (self):
        if (self.item.discount_price):
            return self.quantity * self.item.discount_price
        return self.quantity * self.item.price

    def get_amount_saved(self):
        if (self.item.discount_price):
            return self.quantity*self.item.price - self.quantity * self.item.discount_price
        return 0



class Order(models.Model):
    user = models.ForeignKey (User, on_delete= models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date  = models.DateTimeField()
    ordered = models.BooleanField(default= False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=  models.SET_NULL, blank= True,
                                        null= True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True,
                                        null=True)

    def __str__(self):
        return self.user.username

    def get_total (self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_price()
        return total

class BillingAddress(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    #address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    #default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    price = models.FloatField()
    stripe_charge_id = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

class Coupon(models.Model) :
    code = models.CharField(max_length = 15)

    def __str__(self):
        return self.code

e_commerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  {% load static %}
  {% load cart_template_tags %}
  <title>Material Design Bootstrap</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %} " rel="stylesheet">

  {% block extra_head %}

  {% endblock %}
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>
<body>

 <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/" >
        <strong class="blue-text">E-Commerse DJANGO</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'dj_e_commerce:home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>


        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'dj_e_commerce:order-summary' %}">
              <span class="badge red z-depth-1 mr-1"> {{request.user| cart_item_count }}</span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'logout' %}" class="nav-link waves-effect">
              <p>Logout</p>
            </a>
          </li>

          {% else %}

          <li class="nav-item">
            <a href="{% url 'login' %}" class="nav-link waves-effect"">
              <p>Login</p>
            </a>
          </li>
          {% endif %}

        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->
 <div style = "padding-top:70px">
{% if messages %}
    {% for message in messages %}
   <div class="alert alert-{{message.tags}}" role="alert">
     {{message}}
   </div>
  {% endfor %}
{% endif %}
 </div>


{% block content %}

{% endblock %}

  <!--Footer-->
  <footer class="page-footer fix-down text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
        role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start
        free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="#" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>


    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
 {% block extra_scripts %}

 {% endblock %}
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %} "></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js'  %} "></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %} "></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>


</body>
</html>

e_commerce/templates/checkout-page.html
{% extends 'base.html' %}
{% block content %}
  <main >
    <div class="container wow fadeIn mt-5">
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">

            {% if form.errors %}
            {% for field in form %}
             {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
            {% endif %}

            <form action="{%url 'dj_e_commerce:checkout' %}" method="POST" class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='street_address' name='street_address' class='form-control' />
                  <label for="street_address" class="">Address</label>

                   {{ error|escape }}

                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='apartment_address' name='apartment_address' class='form-control' />
                  <label for="apartment_address" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='zip' name='zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="same_shipping_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_shipping_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="save_info" id="save_info">
                  <label class="custom-control-label" for="save_info">Save as default shipping address</label>
                </div>

              </div>


              <hr>

              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div>
           <div class="col-md-4 mb-4">
          {% include "order_snippet.html" %}
        </div>

      </div>

    </div>


  </main>
{% endblock %}

e_commerce/templates/order-summary.html
{% extends 'base.html' %}

{% block content %}

<main class=" pt-5">
    <div class="container">

          <table class="table ">
              <thead class="thead-dark ">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Item Title</th>
                  <th scope="col">Price</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Total Price</th>
                </tr>
              </thead>
              <tbody>
                {% for order_item in object.items.all %}
                <tr>
                  <th scope="row">{{forloop.counter}}</th>
                  <td>
                    <a href = "{% url 'dj_e_commerce:product' slug=order_item.item.slug %}"> {{order_item.item.title}} </a>
                  </td>
                  <td>${{order_item.item.get_price}} </td>
                  <td>
                    <a href="{% url 'dj_e_commerce:decrease-quantity' slug=order_item.item.slug %}"> <i class="fas fa-minus"></i></a>
                    {{order_item.quantity}}
                    <a href="{% url 'dj_e_commerce:increase-quantity' slug=order_item.item.slug %}"><i class="fas fa-plus"></i> </a>
                  </td>
                  <td>
                    {% if order_item.item.discount_price %}
                    ${{order_item.get_total_price}}
                    <span class="badge badge-primary"> Saving ${{order_item.get_amount_saved}}</span>
                    {%else%}
                    ${{order_item.get_total_price}}
                    {% endif %}


                  </td>
                </tr>
                {% empty %}
                <p> No items in your cart</p>
              {% endfor %}
              <tr>
                <td colspan = "4">
                  <b> Order Total </b>
                </td>
                <td><b> ${{object.get_total}} </b></td>
              </tr>

                <tr>
            <td colspan="5">
              {% if object.items.all.count > 0%}
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
              {% endif%}
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
              </tbody>
            </table>

    </div>

  </main>
{% endblock %}

e_commerce/templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_total_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

e_commerce/templates/product-page.html
{% extends 'base.html' %}
{%block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{item.image.url}}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{object.get_category_display}}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{object.price}}</del>
              </span>
              <span>${{object.discount_price}}</span>

              {% else %}
              <span>${{object.price}}</span>
              {% endif %}
            </p>

            {%if object.description %}
            <p class="lead font-weight-bold">Description</p>
            <p> {{object.description }} </p>
            {% endif %}

            {% if user.is_authenticated%}

            <form action="{% url 'dj_e_commerce:add-to-cart' slug=object.slug%}" class="" method="POST">
              <!-- Default input -->
              {% csrf_token %}
              <input type="number" name= "quantity" value="1" aria-label="Search" class="" style="width: 100px">
              <button class="btn btn-primary" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

               <!-- Default input -->
              <a class="btn btn-primary"
                 href = "{% url 'dj_e_commerce:remove-from-cart' slug=object.slug%}">
                Remove from cart
               <i class="fas fa-shopping-cart ml-1"></i>
              </a>

            </form>
            {% else %}
              <a href="{% url 'login' %}"> Login in and buy  </a>
            {% endif %}



          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>{{Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.}}</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock %}

e_commerce/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
              <h2>Sign up</h2>
            <hr>
            {% if form.errors %}
            {% for field in form %}
             {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
            {% endif %}
              <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Sign up</button>
              </form>

        </div>
      </div>
    </div>
  </main>
{% endblock %}